---
title: "PSApopoolationChr25"
author: "Casey Flay"
date: "30/09/2020"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(RLinuxModules)
library(glue)
library(tidyverse)
library(here)
library(data.table)
setDTthreads(1)
module("load openlava asub/2.2 bwa/0.7.12 samtools/1.9 bcftools/1.10.2 popoolation2 perlbrew/0.76")#old samtools module loaded for popoolation2
here()
```

```{r bamfiles made in PSApopoolationfiles.Rmd}
malepools  <- as.data.table(grep(paste("HW5YYDSXX*"), list.files(path="."), invert=FALSE, value=TRUE))
malepools  <- malepools[, V2 := str_replace_all(V1, ".bai" , "&.bai")             
                       ][, c("V1", "ftype") := tstrsplit(V2, "&", fixed=TRUE)
                       ][is.na(ftype), .(V1)]
mrgdlowPSA         <- as.data.table(grep(paste("*mrgdlowPSA.bam$"), list.files(path="."), invert=FALSE, value=TRUE))
merged_parent_bams <- as.data.table(grep(paste("*mrgdparents.bam$"), list.files(path="."), invert=FALSE, value=TRUE))

rus_x10 <- as.data.table(paste(list('Russell_mrgdparentsA1.bam', 'Russell_mrgdparentsB2.bam', 'Russell_mrgdparentsC3.bam', 'Russell_mrgdparentsD6.bam', 'Russell_mrgdparentsE11.bam', 'Russell_mrgdparentsF12.bam', 'Russell_mrgdparentsG13.bam', 'Russell_mrgdparentsH14.bam', 'Russell_mrgdparentsI15.bam', 'Russell_mrgdparentsJ16.bam')))

abfiles        <- rbindlist(list(malepools,mrgdlowPSA,merged_parent_bams,rus_x10))

abfiles <- abfiles[, V2 := str_replace_all(V1, ".bam" , "&.bam")
                 ][, V2 := str_replace_all(V2, "HW5YYDSXX_" , "	HW5YYDSXX_&")
                 ][, V2 := str_replace_all(V2, "_mrgdlowPSA" , "&_mrgdlowPSA")
                 ][, V2 := str_replace_all(V2, "_mrgdparents" , "&_mrgdparents&")
                 ][, V2 := str_replace_all(V2, "_L00" , "&_L00")                   
                 ][, c("V3", "x2", "x3", "x4") := tstrsplit(V2, "&", fixed=TRUE)]
abfiles <- abfiles[V3=="Russell", V1 := "Russell_mrgdparents.bam"]
  
abfiles <-  abfiles[x2=="A1" | x3=="A1", "malepercentage" := "A1m90"
                  ][x2=="B2" | x3=="B2", "malepercentage" := "B2m75" 
                  ][x2=="C3" | x3=="C3", "malepercentage" := "C3m60"                    
                  ][x2=="D6" | x3=="D6", "malepercentage" := "D6m44"                    
                  ][x2=="E11" | x3=="E11", "malepercentage" := "E11m80"                    
                  ][x2=="F12" | x3=="F12", "malepercentage" := "F12m50"                    
                  ][x2=="G13" | x3=="G13", "malepercentage" := "G13m45"
                  ][x2=="H14" | x3=="H14", "malepercentage" := "H14m68"  
                  ][x2=="I15" | x3=="I15", "malepercentage" := "I15m21"                    
                  ][x2=="J16" | x3=="J16", "malepercentage" := "J16m11"]

mps <-     unique(abfiles[,na.omit(malepercentage)])

```

```{r pools for mpileup using samtools/0.1.18. which will be run through mpileup2sync.jar}
module("unload samtools")
module ("load samtools/0.1.18")

for (i in mps){
submit_mpileup <- function(reference = "*.fa.gz", output = c(), bamfiles = c(), job.init = "asub", job.opts = "-q normal") {
  cmd          <- "samtools mpileup -B -r 'chr25' -f {reference} {bamfiles} > {out}" 
  tmpf         <- tempfile(pattern = "submit_mileup.", fileext = ".sh")
  writeLines(text = c(glue(cmd)), con = tmpf)
  submit       <- "{job.init} {job.opts} {tmpf}"
  system(glue(submit), intern = TRUE)
}

bamfiles <- abfiles[malepercentage=={i}, V1]
file.exists(bamfiles)
out         <- glue("{i}_mp_ru_sampile_chr25.vcf")
reference   <- dir("/workspace/hrards/projects/hrtcdf/genome/fasta", pattern = ".*\\.gz$", full.names = TRUE)
#file.exists(reference)
#submit_mpileup(reference = reference, output = out, bamfiles = bamfiles)
}
```

```{r files dt}
pofiles <- as.data.table(grep(".vcf$", list.files(path="."), invert=FALSE, value=TRUE))
pofiles <- pofiles[, V2 := str_replace_all(V1, "_sampile_" , "&_sampile_")]
pofiles <- pofiles[, V2 := str_replace_all(V2, "_chr25.vcf" , "&_chr25.vcf")]
pofiles <- pofiles[, V2 := str_replace_all(V2, "sampile_parents_" , "sampile_parents_&")
                 ][, c("V3", "V4", "V5") := tstrsplit(V2, "&", fixed=TRUE)
                 ][, V2:=NULL]
pofiles <- pofiles[, "sync" := ".sync"]# for next step
```

```{r rest make sync files with mpileup2sync}
mp <- grep(".vcf$", list.files(path="."), invert=FALSE, value=TRUE)

file.exists(mp)
for (i in mp){
cmd          <- glue::glue("java -ea -Xmx16g -jar  /software/bioinformatics/popoolation2-1201/mpileup2sync.jar --input {i} --output {i}.sync --fastq-type sanger --min-qual 20 --threads 8")
outer        <- "a15";  logD<- here("logD");  bsO<- file.path(logD, paste0(outer,".out")); bsE<- file.path(logD, paste0(outer,".err"))
bsub_cmd     <- glue("bsub -n 8 -o {bsO} -e {bsE} {cmd}")
system(bsub_cmd)
}
```



```{r run CMH test - not running yet as i dont know what to insert into input if pools are compared in population}
m     <- pofiles[malepercentage=="m90", V1]
parents <- pofiles[V4=="Russell", V1]

cmd          <- glue::glue("perl /software/bioinformatics/popoolation2-1201/cmh-test.pl --min-count 6 --mincoverage 4 --max-coverage 250 --population {m},{parents} --input smallcmh.sync --output cmhtest.txt")
outer        <- "atest";  logD<- here("logD");  bsO<- file.path(logD, paste0(outer,".out")); bsE<- file.path(logD, paste0(outer,".err"))
bsub_cmd     <- glue("bsub -n 8 -o {bsO} -e {bsE} {cmd}")
system(bsub_cmd)
```

```{r}
mpsync     <- paste0(mp, ".sync")
file.exists(mpsync)

for (i in mpsync){
cmd          <- glue::glue("perl /software/bioinformatics/popoolation2-1201/snp-frequency-diff.pl --input {i} --output-prefix {i}snp_fd --min-count 6 --min-coverage 50 --max-coverage 200")
outer        <- "a16";  logD<- here("logD");  bsO<- file.path(logD, paste0(outer,".out")); bsE<- file.path(logD, paste0(outer,".err"))
bsub_cmd     <- glue("bsub -n 8 -o {bsO} -e {bsE} {cmd}")
system(bsub_cmd)
}
```

```{r harsh resample of sync files - mainly needed once subsampling from all chromosomes}
bamin        <- paste(pofiles$V1, pofiles$sync, sep="")
file.exists(bamin)
for (i in bamin){
cmd          <- glue::glue("perl /software/bioinformatics/popoolation2-1201/subsample-synchronized.pl --input {i} --output {i}rs --target-coverage 20 --max-coverage 250 --method withreplace")
outer        <- "a11";  logD<- here("logD");  bsO<- file.path(logD, paste0(outer,".out")); bsE<- file.path(logD, paste0(outer,".err"))
bsub_cmd     <- glue("bsub -n 8 -o {bsO} -e {bsE} {cmd}")
system(bsub_cmd)
}
```
```{r update dt}
pofiles <- pofiles[, "syncrs" := ".syncrs"]
```

```{r Make a genebased sync for chr25 and resample}
chr25gff3 <- "/output/genomic/plant/Actinidia/chinensis/Russell/Genome/Assembly/V2a/Gene_models/Archive/Russell_V2a.chromosomes.and.unassigned.renamed.has.stops.gff3"

filein        <- paste0(pofiles$V1, pofiles$syncrs)
file.exists(filein)
for (i in filein){
cmd          <- glue::glue("/software/bioinformatics/popoolation2_1201/create-genewise-sync.pl --input {i} --output {i} \
                            --input ./popoolation/CHR26.resample.sync \
                            --gtf {chr25gff3} \
                            --output ./popoolation/CHR26.resample.genes.sync")
outer        <- "a12";  logD<- here("logD");  bsO<- file.path(logD, paste0(outer,".out")); bsE<- file.path(logD, paste0(outer,".err"))
bsub_cmd     <- glue("bsub -n 8 -o {bsO} -e {bsE} {cmd}")
system(bsub_cmd)
}
```